# Use Node 16.19.1 as the base image
FROM node:16.19.1

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY formikapp/package*.json ./

# Install dependencies
RUN npm install

# Copy the app files to the working directory
COPY formikapp/. .

# Build the React app
RUN npm run build

# Set the command to start the app
CMD [ "npm", "start" ]